# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'robotics_shopping_listFAZcjh.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(681, 636)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(-1, -1, 631, 531))
        self.frame.setStyleSheet(u"/*\n"
"QFrame #frame{\n"
"background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(100, 120, 215, 255), stop:1 rgba(0, 120, 120, 255));\n"
"}\n"
"*/")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.Titleframe = QFrame(self.frame)
        self.Titleframe.setObjectName(u"Titleframe")
        self.Titleframe.setGeometry(QRect(10, 0, 611, 71))
        self.Titleframe.setFrameShape(QFrame.StyledPanel)
        self.Titleframe.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.Titleframe)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 0, 611, 71))
        font = QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setTextFormat(Qt.AutoText)
        self.label.setAlignment(Qt.AlignCenter)
        self.Bottleframe = QFrame(self.frame)
        self.Bottleframe.setObjectName(u"Bottleframe")
        self.Bottleframe.setGeometry(QRect(9, 80, 611, 81))
        self.Bottleframe.setFrameShape(QFrame.StyledPanel)
        self.Bottleframe.setFrameShadow(QFrame.Raised)
        self.quantitybottle = QSpinBox(self.Bottleframe)
        self.quantitybottle.setObjectName(u"quantitybottle")
        self.quantitybottle.setGeometry(QRect(284, 30, 111, 20))
        self.quantitybottle.setStyleSheet(u"border: 1px solid black;\n"
"border-radius: 3px;")
        self.quantitybottle.setAlignment(Qt.AlignCenter)
        self.imagebottle = QLabel(self.Bottleframe)
        self.imagebottle.setObjectName(u"imagebottle")
        self.imagebottle.setGeometry(QRect(20, 0, 131, 81))
        self.imagebottle.setStyleSheet(u"border: 3px solid black;\n"
"border-radius: 5px;")
        self.imagebottle.setPixmap(QPixmap(u"list_items/bottle_green.png"))
        self.imagebottle.setScaledContents(True)
        self.namebottle = QLabel(self.Bottleframe)
        self.namebottle.setObjectName(u"namebottle")
        self.namebottle.setGeometry(QRect(170, 30, 111, 18))
        font1 = QFont()
        font1.setPointSize(13)
        font1.setBold(True)
        font1.setWeight(75)
        self.namebottle.setFont(font1)
        self.namebottle.setAlignment(Qt.AlignCenter)
        self.pricebottle = QLabel(self.Bottleframe)
        self.pricebottle.setObjectName(u"pricebottle")
        self.pricebottle.setGeometry(QRect(390, 28, 61, 21))
        font2 = QFont()
        font2.setPointSize(13)
        font2.setItalic(True)
        font2.setUnderline(False)
        self.pricebottle.setFont(font2)
        self.pricebottle.setAlignment(Qt.AlignCenter)
        self.Clockframe = QFrame(self.frame)
        self.Clockframe.setObjectName(u"Clockframe")
        self.Clockframe.setGeometry(QRect(10, 260, 611, 81))
        self.Clockframe.setFrameShape(QFrame.StyledPanel)
        self.Clockframe.setFrameShadow(QFrame.Raised)
        self.imageclock = QLabel(self.Clockframe)
        self.imageclock.setObjectName(u"imageclock")
        self.imageclock.setGeometry(QRect(20, 0, 131, 81))
        self.imageclock.setStyleSheet(u"border: 3px solid black;\n"
"border-radius: 5px;")
        self.imageclock.setPixmap(QPixmap(u"list_items/clock.jpg"))
        self.imageclock.setScaledContents(True)
        self.nameclock = QLabel(self.Clockframe)
        self.nameclock.setObjectName(u"nameclock")
        self.nameclock.setGeometry(QRect(191, 30, 71, 21))
        self.nameclock.setFont(font1)
        self.nameclock.setAlignment(Qt.AlignCenter)
        self.quantityclock = QSpinBox(self.Clockframe)
        self.quantityclock.setObjectName(u"quantityclock")
        self.quantityclock.setGeometry(QRect(284, 31, 111, 20))
        self.quantityclock.setStyleSheet(u"border: 1px solid black;\n"
"border-radius: 3px;")
        self.quantityclock.setAlignment(Qt.AlignCenter)
        self.priceclock = QLabel(self.Clockframe)
        self.priceclock.setObjectName(u"priceclock")
        self.priceclock.setGeometry(QRect(390, 30, 41, 20))
        self.priceclock.setFont(font2)
        self.priceclock.setAlignment(Qt.AlignCenter)
        self.Checkoutframe = QFrame(self.frame)
        self.Checkoutframe.setObjectName(u"Checkoutframe")
        self.Checkoutframe.setGeometry(QRect(10, 450, 611, 80))
        self.Checkoutframe.setFrameShape(QFrame.StyledPanel)
        self.Checkoutframe.setFrameShadow(QFrame.Raised)
        self.checkoutbutton = QPushButton(self.Checkoutframe)
        self.checkoutbutton.setObjectName(u"checkoutbutton")
        self.checkoutbutton.setGeometry(QRect(530, 30, 75, 23))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(True)
        font3.setWeight(75)
        self.checkoutbutton.setFont(font3)
        self.checkoutbutton.setStyleSheet(u"border: 1px solid black;\n"
"border-radius: 2px;\n"
"background-color:  rgba(255, 255, 255, 255);")
        self.totallcd = QLCDNumber(self.Checkoutframe)
        self.totallcd.setObjectName(u"totallcd")
        self.totallcd.setGeometry(QRect(300, 40, 71, 23))
        self.totallcd.setStyleSheet(u"border: 1px solid black;\n"
"border-radius: 2px;")
        self.total = QLabel(self.Checkoutframe)
        self.total.setObjectName(u"total")
        self.total.setGeometry(QRect(220, 40, 81, 20))
        font4 = QFont()
        font4.setPointSize(11)
        font4.setBold(True)
        font4.setWeight(75)
        self.total.setFont(font4)
        self.pushButton = QPushButton(self.Checkoutframe)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(300, 10, 75, 23))
        self.pushButton.setFont(font3)
        self.pushButton.setStyleSheet(u"border: 1px solid black;\n"
"border-radius: 2px;\n"
"background-color:  rgba(255, 255, 255, 255);")
        self.Cupframe = QFrame(self.frame)
        self.Cupframe.setObjectName(u"Cupframe")
        self.Cupframe.setGeometry(QRect(10, 170, 611, 81))
        self.Cupframe.setFrameShape(QFrame.StyledPanel)
        self.Cupframe.setFrameShadow(QFrame.Raised)
        self.quantitycup = QSpinBox(self.Cupframe)
        self.quantitycup.setObjectName(u"quantitycup")
        self.quantitycup.setGeometry(QRect(284, 30, 111, 20))
        self.quantitycup.setStyleSheet(u"border: 1px solid black;\n"
"border-radius: 3px;")
        self.quantitycup.setAlignment(Qt.AlignCenter)
        self.imagecup = QLabel(self.Cupframe)
        self.imagecup.setObjectName(u"imagecup")
        self.imagecup.setGeometry(QRect(20, 0, 131, 81))
        self.imagecup.setStyleSheet(u"border: 3px solid black;\n"
"border-radius: 5px;")
        self.imagecup.setPixmap(QPixmap(u"list_items/cup.png"))
        self.imagecup.setScaledContents(True)
        self.namecup = QLabel(self.Cupframe)
        self.namecup.setObjectName(u"namecup")
        self.namecup.setGeometry(QRect(180, 20, 91, 41))
        self.namecup.setFont(font1)
        self.namecup.setAlignment(Qt.AlignCenter)
        self.pricecup = QLabel(self.Cupframe)
        self.pricecup.setObjectName(u"pricecup")
        self.pricecup.setGeometry(QRect(390, 28, 41, 20))
        self.pricecup.setFont(font2)
        self.pricecup.setAlignment(Qt.AlignCenter)
        self.Fruitsframe = QFrame(self.frame)
        self.Fruitsframe.setObjectName(u"Fruitsframe")
        self.Fruitsframe.setGeometry(QRect(10, 350, 611, 81))
        self.Fruitsframe.setFrameShape(QFrame.StyledPanel)
        self.Fruitsframe.setFrameShadow(QFrame.Raised)
        self.nameapple = QLabel(self.Fruitsframe)
        self.nameapple.setObjectName(u"nameapple")
        self.nameapple.setGeometry(QRect(320, 55, 41, 21))
        font5 = QFont()
        font5.setPointSize(11)
        font5.setBold(True)
        font5.setItalic(False)
        font5.setUnderline(False)
        font5.setWeight(75)
        font5.setStrikeOut(False)
        self.nameapple.setFont(font5)
        self.nameapple.setAlignment(Qt.AlignCenter)
        self.imagefruits = QLabel(self.Fruitsframe)
        self.imagefruits.setObjectName(u"imagefruits")
        self.imagefruits.setGeometry(QRect(20, 0, 131, 81))
        self.imagefruits.setStyleSheet(u"border: 3px solid black;\n"
"border-radius: 5px;")
        self.imagefruits.setPixmap(QPixmap(u"list_items/fruits.jpg"))
        self.imagefruits.setScaledContents(True)
        self.quantitybanana = QSpinBox(self.Fruitsframe)
        self.quantitybanana.setObjectName(u"quantitybanana")
        self.quantitybanana.setGeometry(QRect(460, 32, 101, 20))
        self.quantitybanana.setStyleSheet(u"border: 1px solid black;\n"
"border-radius: 3px;")
        self.quantitybanana.setAlignment(Qt.AlignCenter)
        self.namebanana = QLabel(self.Fruitsframe)
        self.namebanana.setObjectName(u"namebanana")
        self.namebanana.setGeometry(QRect(480, 55, 51, 21))
        self.namebanana.setFont(font5)
        self.namebanana.setAlignment(Qt.AlignCenter)
        self.namefruits = QLabel(self.Fruitsframe)
        self.namefruits.setObjectName(u"namefruits")
        self.namefruits.setGeometry(QRect(200, 30, 52, 21))
        self.namefruits.setFont(font1)
        self.namefruits.setAlignment(Qt.AlignCenter)
        self.quantityapple = QSpinBox(self.Fruitsframe)
        self.quantityapple.setObjectName(u"quantityapple")
        self.quantityapple.setGeometry(QRect(284, 32, 111, 20))
        self.quantityapple.setStyleSheet(u"border: 1px solid black;\n"
"border-radius: 3px;")
        self.quantityapple.setAlignment(Qt.AlignCenter)
        self.priceapple = QLabel(self.Fruitsframe)
        self.priceapple.setObjectName(u"priceapple")
        self.priceapple.setGeometry(QRect(390, 30, 51, 20))
        self.priceapple.setFont(font2)
        self.priceapple.setAlignment(Qt.AlignCenter)
        self.pricebanana = QLabel(self.Fruitsframe)
        self.pricebanana.setObjectName(u"pricebanana")
        self.pricebanana.setGeometry(QRect(558, 30, 51, 20))
        self.pricebanana.setFont(font2)
        self.pricebanana.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 0, 631, 531))
        self.label_2.setStyleSheet(u"background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(100, 138, 159, 255), stop:1 rgba(45, 35, 56, 255));")
        self.label_2.setScaledContents(True)
        self.label_2.raise_()
        self.Titleframe.raise_()
        self.Bottleframe.raise_()
        self.Clockframe.raise_()
        self.Checkoutframe.raise_()
        self.Cupframe.raise_()
        self.Fruitsframe.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Shopping List", None))
        self.imagebottle.setText("")
        self.namebottle.setText(QCoreApplication.translate("MainWindow", u"Bottle", None))
        self.pricebottle.setText(QCoreApplication.translate("MainWindow", u"$ 0.25", None))
        self.imageclock.setText("")
        self.nameclock.setText(QCoreApplication.translate("MainWindow", u"Clock", None))
        self.priceclock.setText(QCoreApplication.translate("MainWindow", u"$ 7", None))
        self.checkoutbutton.setText(QCoreApplication.translate("MainWindow", u"Checkout", None))
        self.total.setText(QCoreApplication.translate("MainWindow", u"Total $", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.imagecup.setText("")
        self.namecup.setText(QCoreApplication.translate("MainWindow", u"Cup", None))
        self.pricecup.setText(QCoreApplication.translate("MainWindow", u"$ 2", None))
        self.nameapple.setText(QCoreApplication.translate("MainWindow", u"Apple", None))
        self.imagefruits.setText("")
        self.namebanana.setText(QCoreApplication.translate("MainWindow", u"Banana", None))
        self.namefruits.setText(QCoreApplication.translate("MainWindow", u"Fruits", None))
        self.priceapple.setText(QCoreApplication.translate("MainWindow", u"$ 0.1", None))
        self.pricebanana.setText(QCoreApplication.translate("MainWindow", u"$ 0.1", None))
        self.label_2.setText("")
    # retranslateUi

