# Costmap local parameters
local_costmap:
  publish_frequency: 5.0     # Frequency at which to publish the costmap
  width: 6.0                 # Width of the costmap
  height: 6.0                # Height of the costmap
  resolution: 0.05           # Resolution of the costmap (meters/cell)
  static_map: false          # Whether to use a static map (false for dynamic maps)
  rolling_window: true       # Whether to use a rolling window (true for mobile robots)
  transform_tolerance: 0.5   # Time tolerance for waiting for transforms
  update_frequency: 5.0
  robot_base_frame: link_chassis
  global_frame: odom