# Costmap global parameters
global_costmap:
  publish_frequency: 5.0     # Frequency at which to publish the costmap
  resolution: 0.05           # Resolution of the costmap (meters/cell)
  static_map: true           # Whether to use a static map (false for dynamic maps)
  transform_tolerance: 0.5   # Time tolerance for waiting for transforms
  robot_base_frame: link_chassis
  global_frame: map